---
# Rename file to secrets.yml to get started for development or test
# Keep UPDATED REDIS URLs!!! Specially when debugging!!!

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret
  MSG_KEY: IIfDXfB/4kZeQNzMdeVSKvwpGEXEhfgcY0IURH4iqr0=
  SIGNING_KEY: d4fbm0GqEl3HIrCnZM1u35L3eRfFoNwhsufWLYasmw8=
  REDIS_TLS_URL: <provision Redis instance; provide redis URL for dev/test>
  GH_OAUTH_URL: https://github.com/login/oauth/authorize
  GH_TOKEN_URL: https://github.com/login/oauth/access_token
  GH_SCOPE: user:email
  GH_CLIENT_ID: <provision ID/SECRET on Github>
  GH_CLIENT_SECRET: <provision ID/SECRET on Github>

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret
  MSG_KEY: IIfDXfB/4kZeQNzMdeVSKvwpGEXEhfgcY0IURH4iqr0=
  SIGNING_KEY: d4fbm0GqEl3HIrCnZM1u35L3eRfFoNwhsufWLYasmw8=
  REDIS_TLS_URL: <provision Redis instance; provide redis URL for dev/test>
  GH_OAUTH_URL: https://github.com/login/oauth/authorize
  GH_TOKEN_URL: https://github.com/login/oauth/access_token
  GH_SCOPE: user:email
  GH_CLIENT_ID: <provision ID/SECRET on Github>
  GH_CLIENT_SECRET: <provision ID/SECRET on Github>

production:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: <rake generate:session_secret>
  MSG_KEY: IIfDXfB/4kZeQNzMdeVSKvwpGEXEhfgcY0IURH4iqr0=
  SIGNING_KEY: d4fbm0GqEl3HIrCnZM1u35L3eRfFoNwhsufWLYasmw8=
  REDIS_TLS_URL: <provision Redis instance; provide TLS rediss URL for production>
  GH_OAUTH_URL: https://github.com/login/oauth/authorize
  GH_TOKEN_URL: https://github.com/login/oauth/access_token
  GH_SCOPE: user:email
  GH_CLIENT_ID: <provision ID/SECRET on Github>
  GH_CLIENT_SECRET: <provision ID/SECRET on Github>